Vagrant.configure("2") do |config|

  # VM 1: green vm 
  config.vm.define "green" do |green|
      green.vm.box = "bento/ubuntu-20.04"
      green.vm.hostname = "green_for_testing"
      green.vm.network "private_network", ip: "192.168.57.11"
      green.vm.network "forwarded_port", guest: 8080, host: 8027  # Port forwarding for the app
      green.vm.network "forwarded_port", guest: 8082, host: 8028  # Port forwarding for the H2 web console

      
      green.vm.synced_folder "./data", "/home/vagrant/data"
  
      green.vm.provider "vmware_workstation" do |vb|
        vb.gui = true
        vb.memory = "1024"
        vb.cpus = 2 
      end
    end

  # VM 2: blue vm 
  config.vm.define "blue" do |blue|
    blue.vm.box = "bento/ubuntu-20.04"
    blue.vm.hostname = "blue_backup"
    blue.vm.network "private_network", ip: "192.168.57.10"
    
    blue.vm.synced_folder "./data", "/home/vagrant/data"
    blue.vm.network "forwarded_port", guest: 8080, host: 8081  # Port forwarding for the app
    blue.vm.network "forwarded_port", guest: 8080, host: 8082 # Port forwarding for the H2 web console

    blue.vm.provider "vmware_workstation" do |vb|
      vb.gui = true
      vb.memory = "2048"
      vb.cpus = 2 
    end
    SHELL
  end
end
